apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: helm-demo-dev

resources:
  - ../../../base/helm-demo

images:
  - name: operez11/helm-demo
    newName: operez11/helm-demo
    newTag: dev