apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argo-gitops
spec:
  project: default
  source:
    repoURL: https://pkgs.tailscale.com/helmcharts
    chart: tailscale-operator
    targetRevision: 1.78.3
    helm:
      parameters:
        - name: oauth.clientId
          value: "kodn1z5P8F11CNTRL"
        - name: oauth.clientSecret
          value: "tskey-client-kodn1z5P8F11CNTRL-rzdpL8PrGBefNHZuAzT2CewycYAbyFdri"
        - name: operatorConfig.hostname
          value: "tailscale-operator"
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true