apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: medtracker-prod

resources:
  - ../../../base/medtracker/base
  - pvc.yaml
  - ingress.yaml

replicas:
  - name: medtracker
    count: 2
