apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kustomize-dev

resources:
  - ../../../base/kustomize-demo

replicas:
  - name: kustomize-demo
    count: 2

patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: kustomize-demo-html

commonLabels:
  environment: development