apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: medtracker-dev

resources:
  - ../../../base/medtracker/base

replicas:
  - name: medtracker
    count: 1

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: medtracker
    path: deployment-patch.yaml