apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: medtracker-dev

resources:
  - ../../../base/medtracker/base

replicas:
  - name: medtracker
    count: 1

patches:
  - path: deployment-patch.yaml