apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-demo-dev
  namespace: argo-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/OPerezSandoval/homelab-gitops.git
    targetRevision: main
    path: kubernetes/apps/overlays/dev/kustomize-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: kustomize-demo-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-demo-prod
  namespace: argo-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/OPerezSandoval/homelab-gitops.git
    targetRevision: main
    path: kubernetes/apps/overlays/prod/kustomize-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: kustomize-demo-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true