apiVersion: v1
kind: Namespace
metadata:
  name: kustomize-demo-dev
  labels:
    name: kustomize-demo-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: kustomize-demo-prod
  labels:
    name: kustomize-demo-prod