apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: helm-demo-prod

helmCharts:
  - name: new-demo-app
    repo: ../../../base/helm-demo/chart
    releaseName: helm-demo-prod
    namespace: helm-demo-prod
    valuesFile: values.yaml
    includeCRDs: false

images:
  - name: operez11/helm-demo
    newName: operez11/helm-demo
    newTag: prod-latest

resources:
  - ../../../base/helm-demo