apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kustomize-demo-prod

resources:
  - ../../../base/kustomize-demo/base

replicas:
  - name: kustomize-demo
    count: 4

patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: kustomize-demo-html

commonLabels:
  environment: production