apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: med-tracker
  namespace: argo-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/OPerezSandoval/homelab-gitops.git
    targetRevision: main
    path: kubernetes/apps/base/medtracker/base
  destination:
    server: https://kubernetes.default.svc
    namespace: medtracker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true