# kubernetes/apps/base/helm-demo/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-demo-dev
  namespace: argo-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/OPerezSandoval/homelab-gitops.git
    targetRevision: main
    path: kubernetes/apps/overlays/dev/helm-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: helm-demo-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true