apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: med-tracker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OPerezSandoval/homelab-gitops.git
    targetRevision: main
    path: kubernetes/apps/overlays/dev/med-tracker
  destination:
    server: https://kubernetes.default.svc
    namespace: med-tracker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true