apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argo-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/OPerezSandoval/homelab-gitops
    targetRevision: main
    path: kubernetes/apps/base/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-gitops
  syncPolicy:
    automated:
      prune: false  
      selfHeal: true